disabled_rules: # rule identifiers to exclude from running
- identifier_name
- force_cast

opt_in_rules: # some rules are only opt-in
# - attributes
- closure_end_indentation
- closure_parameter_position
- closure_spacing
- collection_alignment
# - conditional_returns_on_newline
- contains_over_first_not_nil
- convenience_type
- discouraged_optional_boolean
- discouraged_optional_collection
- empty_count
- empty_string
# - empty_xctest_method
# - explicit_acl
# - explicit_enum_raw_value
- explicit_init
- fallthrough
- fatal_error_message
# - file_header
- implicit_return
# - implicitly_unwrapped_optional
- joined_default_parameter
- last_where
- legacy_multiple
- legacy_random
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
# - missing_docs
- modifier_order
- multiline_arguments
# - multiline_arguments_brackets
- multiline_function_chains
# - multiline_literal_brackets
- multiline_parameters
# - multiline_parameters_brackets
- multiple_closures_with_trailing_closure
- no_extension_access_modifier
- nslocalizedstring_key
# - number_separator
- operator_usage_whitespace





# Find all the available rules by running:
# swiftlint rules

included: # paths to include during linting. `--path` is ignored if present.
- Sources
- Tests
excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- .build
# - Source/ExcludedFolder
# - Source/ExcludedFile.swift

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# force_cast: warning # implicitly
# force_try:
# severity: warning # explicitly

# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 140
# they can set both implicitly with an array
# type_body_length:
# - 300 # warning
# - 400 # error
# or they can set both explicitly
# file_length:
# warning: 500
# error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
# type_name:
# min_length: 4 # only warning
# max_length: # warning and error
# warning: 40
# error: 50
# excluded: iPhone # excluded via string
# identifier_name:
# min_length: # only min_length
# error: 4 # only error
# excluded: # excluded via string array
# - id
# - URL
# - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
